### ISSUE TITLE
Read the Docs link dead

### ISSUE THREAD

**Issue by Dax911** [Ne0nd0g/merlin-cli#3]
https://github.com/Ne0nd0g/merlin-cli/blob/62c2a9be134805d94d1ed06e6c427a2b5ceb46bf/services/cli/cli.go#L387

It looks like this line redirects to a dead link. I get a 404 when I click it. What link would be best to replace it with?

**Comment by Ne0nd0g** [comment]
@Dax911 Thanks for bringing this up. I'll updated it to the following link in the next release https://merlin-c2.readthedocs.io/en/latest/

**Comment by Dax911** [comment]
Oh no problem, happy to help.
